name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Install and test
      run: |
        yarn install --frozen-lockfile
        yarn test
      env:
        CI: true
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Install and build
      run: |
        yarn install --frozen-lockfile
        yarn run pkg
      env:
        CI: true
    - name: Upload binaries
      uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: dist
